name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-names:
        description: The name of the deployable artifact files 
        required: true 
        default: dist ###
        type: string
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.CodeFromReusableDeploy.outputs.outcome }}
jobs:
  CodeFromReusableDeploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.let-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/download-artifact@v7 
        with:
          name: ${{ inputs.artifact-names }}
      - name: List Files 
        run: ls
      - name: Output information
        run: echo "Deploying and uploading"
      - name: Set result output 
        id: set-result
        run: echo "let-result=success" >> $GITHUB_OUTPUT