name: Reusable Deploy
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3 
      - name: Deplyin the code
        run: echo "Deplying the build"